# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: WiseCleaner.WiseDiskCleaner
PackageVersion: 10.9.8
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://downloads.wisecleaner.com/soft/WDCFree_10.9.8.814.exe
  InstallerSha256: F26E0B59A0CC02345644EAE6560B1C93EA50C2F17FEF242B7DE4B23D243CDEBE
ManifestType: installer
ManifestVersion: 1.4.0
